import type { Exercise } from './types';

export const EXERCISES: Exercise[] = [
  // ── 가슴 ──
  { id: 'db-bench-press', name: '덤벨 벤치프레스', pattern: 'horizontal_push', category: '가슴',
    note: '각도조절벤치 플랫 활용',
    coefficients: { '가슴': 1, '전면삼각근': 0.5, '삼두': 0.5 } },
  { id: 'incline-db-bench-press', name: '인클라인 덤벨 벤치프레스', pattern: 'horizontal_push', category: '가슴',
    note: '벤치 각도 조절로 윗가슴 타겟',
    coefficients: { '가슴': 1, '전면삼각근': 0.5, '삼두': 0.5 } },
  { id: 'db-fly', name: '덤벨 플라이', pattern: 'chest_isolation', category: '가슴',
    note: '벤치 활용 가슴 고립 운동',
    coefficients: { '가슴': 1 } },
  { id: 'db-guillotine-press', name: '덤벨 길로틴 프레스', pattern: 'horizontal_push', category: '가슴',
    note: '벤치 활용, 가슴 전체 타겟',
    coefficients: { '가슴': 1, '전면삼각근': 0.5, '삼두': 0.5 } },
  { id: 'chest-dips', name: '딥스', pattern: 'horizontal_push', category: '가슴',
    note: '치닝디핑 활용. 없으면 디클라인 덤벨 프레스 또는 클로즈 그립 덤벨 프레스로 대체',
    coefficients: { '가슴': 1, '전면삼각근': 0.5, '삼두': 1 } },

  // ── 등 ──
  { id: 'chest-supported-db-row', name: '체스트 서포티드 덤벨 로우', pattern: 'horizontal_pull', category: '등',
    note: '인클라인 벤치에 가슴을 대고 수행. 기립근 부담 없이 등 중상부 타겟',
    coefficients: { '광배/등': 0.5, '중상부/등': 1, '후면삼각근': 0.5, '이두': 0.5 } },
  { id: 'pullup-overhand', name: '오버핸드 그립 풀업', pattern: 'vertical_pull', category: '등',
    note: '문틀철봉 활용 (광배근, 대원근)',
    coefficients: { '광배/등': 1, '중상부/등': 0.5, '이두': 0.5 } },
  { id: 'pullup-neutral', name: '뉴트럴 그립 풀업', pattern: 'vertical_pull', category: '등',
    note: '문틀철봉 + 모스트그립 소품 장착',
    coefficients: { '광배/등': 1, '중상부/등': 0.5, '이두': 0.5 } },
  { id: 'one-arm-db-row', name: '원암 덤벨 로우', pattern: 'horizontal_pull', category: '등',
    note: '크록 로우와 대체관계',
    coefficients: { '광배/등': 1, '중상부/등': 0.5, '후면삼각근': 0.5, '이두': 0.5, '기립근': 0.5 } },
  { id: 'kroc-row', name: '크록 로우', pattern: 'horizontal_pull', category: '등',
    note: '고중량 덤벨 로우 변형. 원암 덤벨 로우와 대체관계',
    coefficients: { '광배/등': 1, '중상부/등': 0.5, '후면삼각근': 0.5, '이두': 0.5, '기립근': 0.5 } },
  { id: 'kelso-shrug', name: '켈소 슈러그', pattern: 'shrug', category: '등',
    note: '팔 굽힘 없이 등 중상부 타겟 가능',
    coefficients: { '중상부/등': 1 } },

  // ── 어깨 ──
  { id: 'db-lateral-raise', name: '사이드 래터럴 레이즈', pattern: 'lateral_raise', category: '어깨',
    note: '몸을 살짝 기울이거나 벤치 활용하여 저항 곡선 개선',
    coefficients: { '측면삼각근': 1 } },
  { id: 'seated-db-shoulder-press', name: '시티드 덤벨 숄더 프레스', pattern: 'vertical_push', category: '어깨',
    note: '벤치에 앉아서 전면/측면 삼각근 타겟',
    coefficients: { '측면삼각근': 0.5, '전면삼각근': 1, '삼두': 0.5 } },
  { id: 'lying-db-lateral-raise', name: '라잉 덤벨 래터럴 레이즈', pattern: 'lateral_raise', category: '어깨',
    note: '벤치에 옆으로 누워 수행. 측면삼각근 신장 구간 강조',
    coefficients: { '측면삼각근': 1 } },
  { id: 'prone-db-reverse-fly', name: '라잉 덤벨 리버스 플라이', pattern: 'rear_delt', category: '어깨',
    note: '벤치에 누워 팔을 반대편으로 보낸 채로 수행. 후면삼각근 자극. 신장 구간 강조',
    coefficients: { '후면삼각근': 1 } },

  // ── 하체 ──
  { id: 'bss-standard', name: '불가리안 스플릿 스쿼트 · 기본형', pattern: 'squat', category: '하체',
    note: '상체 중립. 둔근·사두 균등 타겟',
    coefficients: { '사두': 1, '둔근': 1 } },
  { id: 'bss-quad', name: '불가리안 스플릿 스쿼트 · 사두형', pattern: 'squat', category: '하체',
    note: '상체를 세우고 무릎을 앞으로 보내 대퇴사두 강조',
    coefficients: { '사두': 1, '둔근': 0.5 } },
  { id: 'bss-glute', name: '불가리안 스플릿 스쿼트 · 둔근형', pattern: 'squat', category: '하체',
    note: '상체를 기울이고 힙힌지를 강조하여 둔근 강조',
    coefficients: { '사두': 0.5, '둔근': 1, '햄스트링': 0.5 } },
  { id: 'sissy-squat', name: '시시 스쿼트', pattern: 'squat', category: '하체',
    note: '맨몸/덤벨 활용. 레그익스텐션 대체',
    coefficients: { '사두': 1 } },
  { id: 'db-walking-lunge', name: '덤벨 워킹 런지', pattern: 'squat', category: '하체',
    note: '마당·층간소음 무관 시 사용 (기본은 BSS로 대체)',
    coefficients: { '사두': 1, '둔근': 1 } },
  { id: 'nordic-ham-curl', name: '노르딕 햄스트링 컬', pattern: 'knee_flexion', category: '하체',
    note: '무릎 굴곡 기능으로 햄스트링 강하게 고립',
    coefficients: { '햄스트링': 1 } },
  { id: 'reverse-hyperextension', name: '리버스 하이퍼', pattern: 'hip_extension', category: '하체',
    note: '벤치 끝에 골반을 걸치고 다리를 들어 후면사슬 타겟',
    coefficients: { '둔근': 0.5, '햄스트링': 1, '기립근': 0.5 } },
  { id: 'b-stance-rdl', name: '덤벨 스플릿 스탠드 RDL', pattern: 'hinge', category: '하체',
    note: '뒷발을 킥스탠드처럼 두고 한쪽 다리에 부하 집중. 힙힌지로 햄스트링 신장성 수축 극대화',
    coefficients: { '둔근': 0.5, '햄스트링': 1, '기립근': 0.5 } },
  { id: 'single-leg-db-hip-thrust', name: '싱글 레그 덤벨 힙 스러스트', pattern: 'hip_extension', category: '하체',
    note: '벤치에 등을 대고 한 발로 수행',
    coefficients: { '둔근': 1, '햄스트링': 0.5 } },

  // ── 팔 ──
  { id: 'one-arm-db-oh-extension', name: '원암 덤벨 오버헤드 익스텐션', pattern: 'elbow_extension', category: '팔',
    note: '어깨 굴곡 상태에서 수행 → 삼두 장두 신장 극대화',
    coefficients: { '삼두': 1 } },
  { id: 'db-skull-crusher', name: '덤벨 스컬 크러셔', pattern: 'elbow_extension', category: '팔',
    note: '벤치와 덤벨 활용. 삼두 전체(장두 신장 극대화)',
    coefficients: { '삼두': 1 } },
  { id: 'db-preacher-curl', name: '덤벨 프리처 컬', pattern: 'elbow_flexion', category: '팔',
    note: '각도조절벤치 등받이에 팔을 걸치고 수행',
    coefficients: { '이두': 1 } },
  { id: 'hammer-preacher-curl', name: '해머 그립 프리처 컬', pattern: 'elbow_flexion', category: '팔',
    note: '각도조절벤치 등받이 활용 + 해머그립',
    coefficients: { '이두': 1 } },
  { id: 'db-curl', name: '덤벨 컬', pattern: 'elbow_flexion', category: '팔',
    note: '덤벨 활용 기본 이두 운동',
    coefficients: { '이두': 1 } },
  { id: 'db-hammer-curl', name: '덤벨 해머 컬', pattern: 'elbow_flexion', category: '팔',
    note: '상완근·상완요골근 비중이 높음',
    coefficients: { '이두': 1 } },
  { id: 'incline-db-curl', name: '인클라인 덤벨 컬', pattern: 'elbow_flexion', category: '팔',
    note: '인클라인 벤치를 활용해 이두 신장 구간 강조',
    coefficients: { '이두': 1 } },
];
